### ISSUE TITLE
Very interesting work! Will you release the Automated Manga Translation tools available online or release the API?

### ISSUE THREAD

**Issue by massltime** [mantra-inc/open-mantra-dataset#2]
This an excellent work in AAAI-2021! 
May I have a try to translate the manga now? Will you release the Automated Manga Translation tools available online or release the API?
Besides, does it allow the users to fine-tune the translation results? 

Thanks!

**Comment by rhina** [comment]
Thank you for your interests in our work!
We don't have plan to release the translation API for manga reader because of the copyright issue.

For manga artists and publishers, our tool "MantraEngine" will support the translation of manga by the combination of machine translation and human post-editing. See videos below for the details.
https://www.youtube.com/watch?v=X3gRg6pOXBw
(please enable the English caption)
